<a href="https://colab.research.google.com/github/SelviTriJayanti99/Revisi_Numpy/blob/main/Selvi%20Tri%20Jayanti.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#membuat list
my_list = [99, "Selvi", 4.12, True]
print(my_list)

#menambahkan elemen
my_list.append("Sigma")
print(my_list)

#menghapus elemen
my_list.remove(99)

#update elemen
my_list[1] = "Mama Papa"

#menampilkan list langsung
print("Isi list:", my_list)

[99, 'Selvi', 4.12, True]
[99, 'Selvi', 4.12, True, 'Sigma']
Isi list: ['Selvi', 'Mama Papa', True, 'Sigma']


In [ ]:
import array as arr

#membuat array bertipe integer
my_array = arr.array('i', [1, 2, 3, 4])

#operasi dasar
my_array.append(4)
my_array.remove(2)
my_array[0] = 10
print("Isi array:", end="")
for x in my_array:
   print(x, end="")

Isi array:10344

In [ ]:
#list
my_list = [20, "Mama", 3.15, True] # campuran data tipe
my_list.append("AY")
print("List:", my_list)

#array dgn modul array
import array as arr
my_array = arr.array('i', [ 1, 2, 3, 4, 5])
my_array.append(6)
print("array(module array):", my_array.tolist())

import numpy as np
np_array = np.array([1,2,3,4,5])
print("Numpy Array:", np_array)
print("Operasi Aritmatika (+30):", np_array + 30)

List: [20, 'Mama', 3.15, True, 'AY']
array(module array): [1, 2, 3, 4, 5, 6]
Numpy Array: [1 2 3 4 5]
Operasi Aritmatika (+30): [31 32 33 34 35]


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr) # [1 2 3 4]

[1 2 3 4]


In [ ]:
matrik_np = np.array([[1,2,3],
                     [4,5,6],
                     [7,8,9]])

#membuat array berisi nol
zeros = np.zeros((3,10)) #array 3×10
print(zeros)

#membuat array berisi 1
ones = np.ones((2,8))
print(ones)

#np.arangen
arr = np.arange(0, 18, 2)
print(arr) #

#np.linspace
linspace=np.linspace(0,8,1)
print(linspace)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
[ 0  2  4  6  8 10 12 14 16]
[0.]


In [ ]:
#np.random.rand
random_arr=np.random.rand(3,5)
print(random_arr)

#atribut array np
arr=np.array([[1,2,3], [4,5,6]])
print(arr.shape)

#ndim: jumlah dimensi(rank) dari array
arr = np.array([[[1, 4], [8,9]]])
print(arr.ndim)

#size: jumlah total elemen dalam array
arr = np.zeros((3,8))
print(arr.size)

[[0.1797431  0.36328604 0.85913002 0.40075513 0.50948307]
 [0.05016444 0.40950674 0.99436539 0.57269755 0.92597729]
 [0.68302145 0.86916521 0.29531862 0.26222291 0.51190703]]
(2, 3)
3
24


In [ ]:
#indexing (akses&elemen)
#1D
arr = np.array([10,80,40,60])
print(arr[0])
print(arr[-1])

#2D
arr = np.array([[1,2], [3,4]])
print(arr[0,1])

#Slicing
#1D
arr = np.arange(10)
print(arr[2:7:2])

#2D
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[0:2, 1:3])

10
60
2
[2 4 6]
[[2 3]
 [5 6]]


In [ ]:
y = np.random.randint(0,10, size=(9,9))
print(y)

[[3 2 8 5 0 8 4 7 0]
 [0 0 3 6 1 6 4 1 9]
 [2 0 9 1 1 2 7 4 4]
 [5 1 0 5 1 7 3 0 6]
 [5 0 7 3 3 0 7 6 9]
 [1 7 7 1 2 3 7 3 7]
 [4 4 6 0 2 1 5 7 3]
 [4 7 7 3 4 6 4 4 4]
 [8 1 9 7 3 9 7 9 1]]


In [ ]:
#Contoh Penerapan
#Studi Kasus: Analisis Rating Anime Harian

import numpy as np
# 1. Buat data rating anime selama 7 hari
rating = np.array([8.5, 8.7, 9.0, 8.9, 9.2, 8.8, 9.1])

# 2. Cek atribut dasar array
print("Shape:", rating.shape)
print("Dimensi:", rating.ndim)
print("Tipe data:", rating.dtype)
print("Jumlah data:", rating.size)

# 3. Slicing: ambil 3 hari pertama
awal = rating[:3]
print("3 hari pertama:", awal)

# 4. Cari 3 rating tertinggi
urut = np.sort(rating)
tertinggi = urut[-3:]
print("3 rating tertinggi:", tertinggi)

# 5. Prediksi rating besok (rata-rata + 0.1)
prediksi = np.zeros(1)
prediksi[0] = np.mean(rating) + 0.1
print("Prediksi rating besok:", prediksi[0])

Shape: (7,)
Dimensi: 1
Tipe data: float64
Jumlah data: 7
3 hari pertama: [8.5 8.7 9. ]
3 rating tertinggi: [9.  9.1 9.2]
Prediksi rating besok: 8.985714285714284


In [ ]:
# Koding T13.1   numpy amin dan numpy amax
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5])
min_value = np.amin(arr)
print("Nilai Minimum:", min_value)
max_value = np.amax(arr)
print("Nilai Maksimum:", max_value)

#Koding T13.2    numpy ptp
# Menghitung rentang (range) dari array
range_value = np.ptp(arr)
print("\nArray:", arr)
print("Rentang:", range_value)

#Koding T13.3 numpy percentile
#Membuat array NumPy
arr = np.array([2, 4, 5, 9, 2, 1, 7, 3, 5])
# Menghitung persentil ke-25 (Q1)
q1 = np.percentile(arr, 25)
# Menghitung persentil ke-50 (median)
median = np.percentile(arr, 50)
# Menghitung persentil ke-75 (Q3)
q3 = np.percentile(arr, 75)
# Menampilkan hasil
print("Q1 (Persentil ke-25):", q1)
print("Median (Persentil ke-50):", median)
print("Q3 (Persentil ke-75):", q3)

#Koding T13.4 Numpy median
# Membuat array NumPy
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5])
# Menggunakan numpy.median() untuk menghitung median
median_value = np.median(arr)
print("Array:", arr)
print("Median:", median_value)

#Koding T13.5 numpy mean
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5])
mean_value = np.mean(arr)
print("Array:", arr)
print("Mean:", mean_value)

#Koding T13.6 numpy averange
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5])
average = np.average(arr)
print(average)

Nilai Minimum: 1
Nilai Maksimum: 9

Array: [3 1 4 1 5 9 2 6 5]
Rentang: 8
Q1 (Persentil ke-25): 2.0
Median (Persentil ke-50): 4.0
Q3 (Persentil ke-75): 5.0
Array: [3 1 4 1 5 9 2 6 5]
Median: 4.0
Array: [3 1 4 1 5 9 2 6 5]
Mean: 4.0
4.0


In [ ]:
#Koding T13.7 standart deviation
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5])
# Menghitung standar deviasi dari array arr
std_deviation = np.std(arr)
print("Standar Deviasi:", std_deviation)

#Koding T13.8  >
# Membuat array NumPy
arr = np.array([2, 1, 4, 5, 7, 4, 6, 3, 1])
#menghitung varian dari array arr
variance = np.var(arr)
print("Array:", arr)
print("Varians:", variance)

Standar Deviasi: 2.449489742783178
Array: [2 1 4 5 7 4 6 3 1]
Varians: 4.0
